name: release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  publish:
    name: publish python library
    timeout-minutes: 60
    runs-on: ledgerhq-shared-small
    steps:
      - name: Checkout
        timeout-minutes: 10
        uses: actions/checkout@v4

      - name: Setup python / PDM
        timeout-minutes: 10
        uses: ./.github/actions/pdm

      - name: Install dependencies
        timeout-minutes: 10
        run: pdm install --dev --check --frozen-lockfile
        env:
          FURY_TOKEN: ${{ secrets.PYPI_DEPLOY_TOKEN}}

      - name: Build distribution artifacts
        timeout-minutes: 10
        run: pdm build

      - name: Upload distribution artifacts to Gemfury
        timeout-minutes: 10
        env:
          PDM_PUBLISH_REPO: https://pypi.fury.io/ledger/
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_DEPLOY_TOKEN}}
        run: pdm publish --no-build
