name: release

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    name: publish python library
    timeout-minutes: 60
    runs-on: ledgerhq-shared-small
    steps:
      - uses: LedgerHQ/actions/python-lib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GREEN_NEXUS_HOST: ${{ secrets.GREEN_NEXUS_HOST }}
          GREEN_NEXUS_USER: ${{ secrets.GREEN_NEXUS_USER }}
          GREEN_NEXUS_PASSWORD: ${{ secrets.GREEN_NEXUS_PASSWORD }}
          PYPI_PUSH_TOKEN: ${{ secrets.PYPI_PUSH_TOKEN }}
          PYPI_DEPLOY_TOKEN: ${{ secrets.PYPI_DEPLOY_TOKEN }}
        with:
          python-version: "3.12"
